/**
 * Unique Wage lookup catalogs. Crew costing still uses the Shahan billed books.
 * East Coast = Amendment 11 PCA0001103. Monroe = CW35353 Exhibit C-1.
 * Yates = Labor Ratebuilder Base Rate (not COMP, not Shahan billed ST).
 * West Coast unique TSV is not in this file yet — Ferndale / Rodeo stay on samples.
 * Never commit the xlsx / PDF.
 */

import type { ShahanLaborRow } from "./shahan-wood-river.ts";

export const BAYWAY_WAGE: ShahanLaborRow[] = [
  { craftName: "SITE LEAD 01", group: "MERIT STAFF", baseSt: 90, st: 138.07, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "SITE LEAD 02", group: "MERIT STAFF", baseSt: 88, st: 135.53, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "MANAGER, PROJECT 01", group: "MERIT STAFF", baseSt: 83.5, st: 129.83, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "MANAGER, PROJECT 02", group: "MERIT STAFF", baseSt: 81.5, st: 127.29, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ENGINEER, PROJECT 01", group: "MERIT STAFF", baseSt: 65, st: 106.37, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ENGINEER, PROJECT 02", group: "MERIT STAFF", baseSt: 63, st: 103.83, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ENGINEER, FIELD 01", group: "MERIT STAFF", baseSt: 68, st: 110.17, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ENGINEER, FIELD 02", group: "MERIT STAFF", baseSt: 66, st: 107.64, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ANALYST, COST 01", group: "MERIT STAFF", baseSt: 83, st: 129.19, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ANALYST, COST 02", group: "MERIT STAFF", baseSt: 80, st: 125.39, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ANALYST, PROJECT CONTROLS 01", group: "MERIT STAFF", baseSt: 85, st: 131.73, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ANALYST, PROJECT CONTROLS 02", group: "MERIT STAFF", baseSt: 80, st: 125.39, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PLANNER ESTIMATOR 01", group: "MERIT STAFF", baseSt: 48.5, st: 85.45, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PLANNER ESTIMATOR 02", group: "MERIT STAFF", baseSt: 46.5, st: 82.91, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PLANNER SCHEDDULER 01", group: "MERIT STAFF", baseSt: 62.5, st: 103.2, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PLANNER SCHEDDULER 02", group: "MERIT STAFF", baseSt: 60.5, st: 100.66, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LEAD QA-QC 01", group: "MERIT STAFF", baseSt: 57, st: 96.23, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LEAD QA-QC 02", group: "MERIT STAFF", baseSt: 55, st: 93.69, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR QA-QC 1", group: "MERIT STAFF", baseSt: 52, st: 89.89, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR QA-QC 2", group: "MERIT STAFF", baseSt: 50, st: 87.35, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LEAD SAFETY 01", group: "MERIT STAFF", baseSt: 48, st: 84.81, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LEAD SAFETY 02", group: "MERIT STAFF", baseSt: 46, st: 82.28, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR SAFETY 01", group: "MERIT STAFF", baseSt: 45, st: 81.01, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR SAFETY 02", group: "MERIT STAFF", baseSt: 43, st: 78.47, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR MATERIAL 01", group: "MERIT STAFF", baseSt: 45, st: 81.01, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR MATERIAL 02", group: "MERIT STAFF", baseSt: 43, st: 78.47, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "CLERK FIELD 01", group: "MERIT STAFF", baseSt: 33, st: 65.79, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "CLERK FIELD 02", group: "MERIT STAFF", baseSt: 30, st: 61.99, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "MANAGER OFFICE 01", group: "MERIT STAFF", baseSt: 43, st: 78.47, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "MANAGER OFFICE 02", group: "MERIT STAFF", baseSt: 41, st: 75.94, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "CLERK OFFICE 01", group: "MERIT STAFF", baseSt: 28, st: 59.45, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "CLERK OFFICE 02", group: "MERIT STAFF", baseSt: 26, st: 56.92, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "CLERK TIMEKEEPER 01", group: "MERIT STAFF", baseSt: 35, st: 68.33, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "CLERK TIMEKEEPER 02", group: "MERIT STAFF", baseSt: 33, st: 65.79, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "CLERK DOCUMENT 01", group: "MERIT STAFF", baseSt: 32, st: 64.53, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "CLERK DOCUMENT 02", group: "MERIT STAFF", baseSt: 30, st: 61.99, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "GENERAL SUPERINTENDENT 01", group: "MERIT STAFF", baseSt: 86.5, st: 133.63, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "GENERAL SUPERINTENDENT 02", group: "MERIT STAFF", baseSt: 82.5, st: 128.56, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "SUPERINTENDENT 01", group: "MERIT STAFF", baseSt: 76.5, st: 120.95, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "SUPERINTENDENT 02", group: "MERIT STAFF", baseSt: 73.5, st: 117.15, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ASST SUPERINTENDENT 01", group: "MERIT STAFF", baseSt: 72, st: 115.25, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ASST SUPERINTENDENT 02", group: "MERIT STAFF", baseSt: 70, st: 112.71, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "SITE LEAD 01", group: "BM STAFF", baseSt: 65, st: 148.59, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "MANAGER PROJECT 01", group: "BM STAFF", baseSt: 62, st: 144.99, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "MANAGER PROJECT 02", group: "BM STAFF", baseSt: 60, st: 142.6, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ENGINEER PROJECT 01", group: "BM STAFF", baseSt: 55, st: 136.61, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ENGINEER PROJECT 02", group: "BM STAFF", baseSt: 50, st: 130.62, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ENGINEER FIELD 01", group: "BM STAFF", baseSt: 58, st: 140.2, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ENGINEER FIELD 02", group: "BM STAFF", baseSt: 54, st: 135.41, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ENGINEER PROJECT 03", group: "BM STAFF", baseSt: 48, st: 128.22, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ENGINEER FIELD 03", group: "BM STAFF", baseSt: 57, st: 139, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PLANNER/ESTIMATOR 01", group: "BM STAFF", baseSt: 55, st: 136.61, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LEAD QA/QC 01", group: "BM STAFF", baseSt: 57, st: 139, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LEAD QA/QC 02", group: "BM STAFF", baseSt: 55, st: 136.61, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR QA-QC 01", group: "BM STAFF", baseSt: 47, st: 127.02, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR QA-QC 02", group: "BM STAFF", baseSt: 44, st: 123.43, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LEAD SAFETY 01", group: "BM STAFF", baseSt: 47, st: 127.02, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LEAD SAFETY 02", group: "BM STAFF", baseSt: 46, st: 125.82, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR SAFETY 01", group: "BM STAFF", baseSt: 41, st: 119.83, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR SUBCONTRACT 01", group: "BM STAFF", baseSt: 45, st: 124.63, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "SUPERINTENDENT GEN BM 01", group: "BM STAFF", baseSt: 60, st: 142.6, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "SUPERINTENDENT BM 01", group: "BM STAFF", baseSt: 58, st: 140.2, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "SUPERINTENDENT PF 01", group: "PF STAFF", baseSt: 66.92, st: 158.84, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "BOILERMAKER FOREMAN GENERAL 01", group: "BOILERMAKER", baseSt: 55.7, st: 136.66, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "BOILERMAKER FOREMAN 01", group: "BOILERMAKER", baseSt: 53.7, st: 133.15, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "BOILERMAKER JOURNEYMAN 01", group: "BOILERMAKER", baseSt: 48.7, st: 125.3, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "BOILERMAKER APPRENTICE 65%", group: "BOILERMAKER", baseSt: 35.17, st: 102.11, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "BOILERMAKER APPRENTICE 70%", group: "BOILERMAKER", baseSt: 37.88, st: 106.33, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "BOILERMAKER APPRENTICE 75%", group: "BOILERMAKER", baseSt: 40.58, st: 110.59, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "BOILERMAKER APPRENTICE 80%", group: "BOILERMAKER", baseSt: 43.29, st: 114.82, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "BOILERMAKER APPRENTICE 85%", group: "BOILERMAKER", baseSt: 45.99, st: 119.07, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "BOILERMAKER APPRENTICE 90%", group: "BOILERMAKER", baseSt: 46.26, st: 120.39, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "BOILERMAKER TOOLROOM", group: "BOILERMAKER", baseSt: 48.7, st: 125.3, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "BOILERMAKER EXPEDITOR", group: "BOILERMAKER", baseSt: 48.7, st: 125.3, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "BOILERMAKER MATERIAL COORDINATOR", group: "BOILERMAKER", baseSt: 48.7, st: 125.3, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LABORER FOREMAN GEN 01", group: "LABORER", baseSt: 47.11, st: 107.79, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LABORER FOREMAN 01", group: "LABORER", baseSt: 41.99, st: 101.66, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LABORER CLASS A 01", group: "LABORER", baseSt: 36.87, st: 95.52, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LABORER CLASS B 01", group: "LABORER", baseSt: 35.97, st: 94.45, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LABORER CLASS C 01", group: "LABORER", baseSt: 30.57, st: 87.98, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LABORER UNION REP", group: "LABORER", baseSt: 37.62, st: 96.42, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "OPERATOR ENG SE A <139FT<100T", group: "OPERATOR", baseSt: 59.02, st: 127.31, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "OPERATOR ENG SE A <139FT>100T", group: "OPERATOR", baseSt: 63.52, st: 132.7, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "OPERATOR ENG SE A >140FT<100T", group: "OPERATOR", baseSt: 60.52, st: 129.1, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "OPERATOR ENG SE A >140FT>100T", group: "OPERATOR", baseSt: 65.02, st: 134.49, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "OPERATOR ENG SE CLASS B", group: "OPERATOR", baseSt: 56.51, st: 124.3, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "OPERATOR ENG SE CLASS C", group: "OPERATOR", baseSt: 54.12, st: 121.43, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "OPERATOR ENG SE CLASS D", group: "OPERATOR", baseSt: 52.74, st: 119.78, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "OPERATOR ENG SE CLASS E", group: "OPERATOR", baseSt: 49.36, st: 115.73, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "OPERATOR ENG SE ENGINEER LEAD", group: "OPERATOR", baseSt: 57.97, st: 126.05, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "OPERATOR ENG SE FOREMAN 01", group: "OPERATOR", baseSt: 57.97, st: 126.05, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "OPERATOR ENG SE ROD/CHAINMN 01", group: "OPERATOR", baseSt: 48.42, st: 114.61, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "OPERATOR ENG LEAD 01", group: "OPERATOR", baseSt: 60.52, st: 130.3, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "Extractor Operator 01", group: "OPERATOR", baseSt: 56.51, st: 124.9, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER FOREMAN GENERAL 01", group: "PIPEFITTER", baseSt: 58.64, st: 148.61, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER FOREMAN GEN ASST 01", group: "PIPEFITTER", baseSt: 57.64, st: 146.49, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER FOREMAN 01", group: "PIPEFITTER", baseSt: 57.14, st: 145.43, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER JOURNEYMAN 01", group: "PIPEFITTER", baseSt: 52.64, st: 135.9, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER APPRENTICE 35%", group: "PIPEFITTER", baseSt: 20.47, st: 73.8, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER APPRENTICE 45%", group: "PIPEFITTER", baseSt: 26.32, st: 84.43, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER APPRENTICE 55%", group: "PIPEFITTER", baseSt: 32.17, st: 95.06, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER APPRENTICE 65%", group: "PIPEFITTER", baseSt: 38.02, st: 105.7, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER APPRENTICE 75%", group: "PIPEFITTER", baseSt: 43.87, st: 116.33, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER WELDER 01", group: "PIPEFITTER", baseSt: 57.14, st: 145.43, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER TOOLROOM", group: "PIPEFITTER", baseSt: 52.64, st: 135.9, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER EXPEDITOR", group: "PIPEFITTER", baseSt: 52.64, st: 135.9, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER MATERIAL COORDINATOR", group: "PIPEFITTER", baseSt: 52.64, st: 135.9, ot: null, dt: null, pd: null, wageSource: "comp" },
];

export const WOOD_RIVER_WAGE: ShahanLaborRow[] = [
  { craftName: "LEAD SITE BOILERMAKER 01", group: "BM STAFF TM", baseSt: 71, st: 141.9, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LEAD SITE BOILERMAKER 02", group: "BM STAFF TM", baseSt: 69, st: 139.48, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "MANAGER PROJECT BOILERMAKER 01", group: "BM STAFF TM", baseSt: 64, st: 133.42, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "MANAGER PROJECT BOILERMAKER 02", group: "BM STAFF TM", baseSt: 53.96, st: 121.25, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ENGINEER PROJECT BLRMKR 01", group: "BM STAFF TM", baseSt: 52.96, st: 120.04, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ENGINEER PROJECT BLRMKR 02", group: "BM STAFF TM", baseSt: 45.96, st: 111.55, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ENGINEER FIELD BOILERMAKER 01", group: "BM STAFF TM", baseSt: 50.96, st: 117.61, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ENGINEER FIELD BOILERMAKER 02", group: "BM STAFF TM", baseSt: 48.96, st: 115.19, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PLANNER ESTIMATOR BLRMKR 01", group: "BM STAFF TM", baseSt: 47.96, st: 113.98, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PLANNER ESTIMATOR BLRMKR 02", group: "BM STAFF TM", baseSt: 45.96, st: 111.55, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PLANNER SCHEDULER BLRMKR 01", group: "BM STAFF TM", baseSt: 48.96, st: 115.19, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PLANNER SCHEDULER BLRMKR 02", group: "BM STAFF TM", baseSt: 45.96, st: 111.55, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LEAD QA-QC BOILERMAKER 01", group: "BM STAFF TM", baseSt: 60, st: 128.57, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LEAD QA-QC BOILERMAKER 02", group: "BM STAFF TM", baseSt: 58, st: 126.15, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR QA/QC BLRMKR 01", group: "BM STAFF TM", baseSt: 57, st: 124.93, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR QA/QC BLRMKR 02", group: "BM STAFF TM", baseSt: 55, st: 122.51, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LEAD SAFETY BOILERMAKER 01", group: "BM STAFF TM", baseSt: 59, st: 127.36, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LEAD SAFETY BOILERMAKER 02", group: "BM STAFF TM", baseSt: 57, st: 124.93, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR SAFETY BLRMKR 01", group: "BM STAFF TM", baseSt: 44, st: 109.18, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR SAFETY BLRMKR 02", group: "BM STAFF TM", baseSt: 42, st: 106.75, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR SUBCON BLRMKR 01", group: "BM STAFF TM", baseSt: 43, st: 107.97, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR SUBCON BLRMKR 02", group: "BM STAFF TM", baseSt: 41, st: 105.54, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR MATERIAL BLRMKR 01", group: "BM STAFF TM", baseSt: 52, st: 118.87, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR MATERIAL BLRMKR 02", group: "BM STAFF TM", baseSt: 50, st: 116.45, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "SUPERINTENDENT BOILERMAKER 01", group: "BM STAFF TM", baseSt: 59, st: 127.36, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "SUPERINTENDENT BOILERMAKER 02", group: "BM STAFF TM", baseSt: 57, st: 124.93, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "SUPERINTENDENT GENERAL BM 01", group: "BM STAFF TM", baseSt: 62, st: 130.99, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "SUPERINTENDENT GENERAL BM 02", group: "BM STAFF TM", baseSt: 60, st: 128.57, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "MANAGER PROJECT PIPEFITTER 01", group: "PF STAFF TM", baseSt: 70.58, st: 127.23, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "MANAGER PROJECT PIPEFITTER 02", group: "PF STAFF TM", baseSt: 67.98, st: 124.04, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "MANAGER PROJECT PIPEFITTER 03", group: "PF STAFF TM", baseSt: 63.98, st: 119.13, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "SUPERINTENDENT GENERAL PF 01", group: "PF STAFF TM", baseSt: 67.5, st: 123.45, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "SUPERINTENDENT GENERAL PF 02", group: "PF STAFF TM", baseSt: 59.9, st: 114.13, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "SUPERINTENDENT GENERAL PF 03", group: "PF STAFF TM", baseSt: 60.9, st: 115.35, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "SUPERINTENDENT PIPEFITTER 01", group: "PF STAFF TM", baseSt: 57.9, st: 111.67, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "SUPERINTENDENT PIPEFITTER 02", group: "PF STAFF TM", baseSt: 55.9, st: 109.22, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "SUPERINTENDENT PIPEFITTER 03", group: "PF STAFF TM", baseSt: 53.9, st: 106.77, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ENGINEER PROJECT PIPFTR 01", group: "PF STAFF TM", baseSt: 55.9, st: 109.22, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ENGINEER FIELD PIPEFITTER 01", group: "PF STAFF TM", baseSt: 53.9, st: 106.77, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PLANNER ESTIMATOR PIPFTR 01", group: "PF STAFF TM", baseSt: 54.9, st: 107.99, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PLANNER ESTIMATOR PIPFTR 02", group: "PF STAFF TM", baseSt: 52.9, st: 105.54, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PLANNER ESTIMATOR PIPFTR 03", group: "PF STAFF TM", baseSt: 50.9, st: 103.09, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PLANNER SCHEDULER PIPFTR 01", group: "PF STAFF TM", baseSt: 53.9, st: 106.77, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PLANNER SCHEDULER PIPFTR 02", group: "PF STAFF TM", baseSt: 51.9, st: 104.32, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LEAD QA-QC PIPEFITTER 01", group: "PF STAFF TM", baseSt: 62.5, st: 117.32, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LEAD QA-QC PIPEFITTER 02", group: "PF STAFF TM", baseSt: 60.9, st: 115.35, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LEAD QA-QC PIPEFITTER 03", group: "PF STAFF TM", baseSt: 58.9, st: 112.9, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR QA/QC PIPFTR 01", group: "PF STAFF TM", baseSt: 52.9, st: 105.54, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR QA/QC PIPFTR 02", group: "PF STAFF TM", baseSt: 52.5, st: 105.05, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR QA/QC PIPFTR 03", group: "PF STAFF TM", baseSt: 52, st: 104.44, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LEAD SAFETY PIPEFITTER 01", group: "PF STAFF TM", baseSt: 54.41, st: 107.39, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR SAFETY PIPFTR 01", group: "PF STAFF TM", baseSt: 53.1, st: 105.79, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR SAFETY PIPFTR 02", group: "PF STAFF TM", baseSt: 52.6, st: 105.17, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR SAFETY PIPFTR 03", group: "PF STAFF TM", baseSt: 52.1, st: 104.56, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR MATERIAL PIPFTR 01", group: "PF STAFF TM", baseSt: 50.9, st: 103.09, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LEAD SITE 01", group: "MERIT STAFF TM", baseSt: 90, st: 139.09, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LEAD SITE 02", group: "MERIT STAFF TM", baseSt: 88, st: 136.53, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "MANAGER, PROJECT 01", group: "MERIT STAFF TM", baseSt: 83.5, st: 130.76, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "MANAGER, PROJECT 02", group: "MERIT STAFF TM", baseSt: 81.5, st: 128.19, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ENGINEER, PROJECT 01", group: "MERIT STAFF TM", baseSt: 65, st: 107.04, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ENGINEER, PROJECT 02", group: "MERIT STAFF TM", baseSt: 63, st: 104.48, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ENGINEER, FIELD 01", group: "MERIT STAFF TM", baseSt: 68, st: 110.89, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ENGINEER, FIELD 02", group: "MERIT STAFF TM", baseSt: 66, st: 108.32, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ANALYST, COST 01", group: "MERIT STAFF TM", baseSt: 83, st: 130.12, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ANALYST, COST 02", group: "MERIT STAFF TM", baseSt: 80, st: 126.27, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ANALYST, PROJECT CONTROLS 01", group: "MERIT STAFF TM", baseSt: 85, st: 132.68, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ANALYST, PROJECT CONTROLS 02", group: "MERIT STAFF TM", baseSt: 80, st: 126.27, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PLANNER ESTIMATOR 01", group: "MERIT STAFF TM", baseSt: 48.5, st: 85.89, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PLANNER ESTIMATOR 02", group: "MERIT STAFF TM", baseSt: 46.5, st: 83.32, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PLANNER SCHEDULER 01", group: "MERIT STAFF TM", baseSt: 62.5, st: 103.84, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PLANNER SCHEDULER 02", group: "MERIT STAFF TM", baseSt: 60.5, st: 101.27, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LEAD QA-QC 01", group: "MERIT STAFF TM", baseSt: 60.5, st: 101.27, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LEAD QA-QC 02", group: "MERIT STAFF TM", baseSt: 58, st: 98.07, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR QA-QC 1", group: "MERIT STAFF TM", baseSt: 64, st: 105.76, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR QA-QC 2", group: "MERIT STAFF TM", baseSt: 57, st: 96.78, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LEAD SAFETY 01", group: "MERIT STAFF TM", baseSt: 52.5, st: 91.02, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LEAD SAFETY 02", group: "MERIT STAFF TM", baseSt: 50.5, st: 88.45, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR SAFETY 01", group: "MERIT STAFF TM", baseSt: 52.5, st: 91.02, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR SAFETY 02", group: "MERIT STAFF TM", baseSt: 50.5, st: 88.45, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR MATERIAL 01", group: "MERIT STAFF TM", baseSt: 45, st: 81.4, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR MATERIAL 02", group: "MERIT STAFF TM", baseSt: 43, st: 78.84, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "CLERK FIELD 01", group: "MERIT STAFF TM", baseSt: 40, st: 74.99, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "CLERK FIELD 02", group: "MERIT STAFF TM", baseSt: 38, st: 72.43, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "MANAGER OFFICE 01", group: "MERIT STAFF TM", baseSt: 55, st: 94.22, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "MANAGER OFFICE 02", group: "MERIT STAFF TM", baseSt: 48, st: 85.25, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "CLERK OFFICE 01", group: "MERIT STAFF TM", baseSt: 32, st: 64.73, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "CLERK OFFICE 02", group: "MERIT STAFF TM", baseSt: 30, st: 62.17, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "CLERK TIMEKEEPER 01", group: "MERIT STAFF TM", baseSt: 38, st: 72.43, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "CLERK TIMEKEEPER 02", group: "MERIT STAFF TM", baseSt: 36, st: 69.86, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "CLERK DOCUMENT 01", group: "MERIT STAFF TM", baseSt: 36, st: 69.86, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "CLERK DOCUMENT 02", group: "MERIT STAFF TM", baseSt: 34, st: 67.3, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "GENERAL SUPERINTENDENT 01", group: "MERIT STAFF TM", baseSt: 86.5, st: 134.6, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "GENERAL SUPERINTENDENT 02", group: "MERIT STAFF TM", baseSt: 82.5, st: 129.48, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "SUPERINTENDENT 01", group: "MERIT STAFF TM", baseSt: 76.5, st: 121.78, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "SUPERINTENDENT 02", group: "MERIT STAFF TM", baseSt: 73.5, st: 117.94, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ASST SUPERINTENDENT 01", group: "MERIT STAFF TM", baseSt: 72, st: 116.01, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ASST SUPERINTENDENT 02", group: "MERIT STAFF TM", baseSt: 70, st: 113.45, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LABORER GENERAL FOREMAN", group: "LABORER TM", baseSt: 38.01, st: 94.21, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LABORER GENERAL FOREMAN ABATE", group: "LABORER TM", baseSt: 38.51, st: 94.82, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LABORER FOREMAN 10-20", group: "LABORER TM", baseSt: 36.51, st: 92.39, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LABORER FOREMAN ABATE 10-20", group: "LABORER TM", baseSt: 37.01, st: 93, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LABORER FOREMAN 03-09", group: "LABORER TM", baseSt: 35.51, st: 91.18, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LABORER FOREMAN ABATE 03-09", group: "LABORER TM", baseSt: 36.01, st: 91.79, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LABORER JOURNEYMAN", group: "LABORER TM", baseSt: 34.51, st: 89.97, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LABORER JOURNEYMAN ABATE", group: "LABORER TM", baseSt: 35.01, st: 90.58, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LABORER APPRENTICE Y4", group: "LABORER TM", baseSt: 32.79, st: 87.88, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LABORER APPRENTICE Y3", group: "LABORER TM", baseSt: 30.88, st: 85.57, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LABORER APPRENTICE Y2", group: "LABORER TM", baseSt: 29.06, st: 83.37, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LABORER APPRENTICE Y1", group: "LABORER TM", baseSt: 27.25, st: 81.16, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "TEAMSTER GRP01", group: "TEAMSTER TM", baseSt: 45.8, st: 97.6, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "TEAMSTER GRP02", group: "TEAMSTER TM", baseSt: 46.35, st: 98.27, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "TEAMSTER GRP03", group: "TEAMSTER TM", baseSt: 46.65, st: 98.64, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "TEAMSTER GRP04", group: "TEAMSTER TM", baseSt: 46.99, st: 99.04, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "TEAMSTER GRP05", group: "TEAMSTER TM", baseSt: 48.04, st: 100.32, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "TEAMSTER GRP06", group: "TEAMSTER TM", baseSt: 49.94, st: 102.62, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "OPERATING ENG GRP 01", group: "OPERATING ENG TM", baseSt: 49.12, st: 112.95, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "OPERATING ENG GRP 02", group: "OPERATING ENG TM", baseSt: 48.04, st: 111.65, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "OPERATING ENG GRP 03", group: "OPERATING ENG TM", baseSt: 43.79, st: 106.49, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "OPERATING ENG GRP 04", group: "OPERATING ENG TM", baseSt: 50.07, st: 114.1, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "OPERATING ENG GRP 05", group: "OPERATING ENG TM", baseSt: 51.02, st: 115.25, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "OPERATING ENG GRP 05B", group: "OPERATING ENG TM", baseSt: 51.25, st: 115.54, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "OPERATING ENG GRP 06", group: "OPERATING ENG TM", baseSt: 51.54, st: 115.88, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "OPERATING ENG GRP 06B", group: "OPERATING ENG TM", baseSt: 51.73, st: 116.11, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "OPERATING ENG GRP 07", group: "OPERATING ENG TM", baseSt: 51.82, st: 116.23, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "OPERATING ENG GRP 07B", group: "OPERATING ENG TM", baseSt: 51.92, st: 116.34, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "OPERATING ENG GRP 07C", group: "OPERATING ENG TM", baseSt: 52.06, st: 116.52, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "OPERATING ENG GRP 08", group: "OPERATING ENG TM", baseSt: 52.11, st: 116.57, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "OPERATING ENG GRP 08B", group: "OPERATING ENG TM", baseSt: 52.2, st: 116.69, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "OPERATING ENG GRP 08C", group: "OPERATING ENG TM", baseSt: 52.35, st: 116.86, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "OPERATING ENG GRP 08D", group: "OPERATING ENG TM", baseSt: 52.68, st: 117.27, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "OPERATING ENG GRP 11", group: "OPERATING ENG TM", baseSt: 51.02, st: 115.25, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "OPERATING ENG GRP 12", group: "OPERATING ENG TM", baseSt: 51.97, st: 116.4, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER GENERAL FOREMAN", group: "PIPEFITTER TM", baseSt: 58.84, st: 111.22, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER FOREMAN", group: "PIPEFITTER TM", baseSt: 53.93, st: 105.28, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER JOURNEYMAN", group: "PIPEFITTER TM", baseSt: 49.03, st: 99.33, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER APPRENTICE 45%", group: "PIPEFITTER TM", baseSt: 23.22, st: 68.06, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER APPRENTICE 50%", group: "PIPEFITTER TM", baseSt: 25.81, st: 71.19, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER APPRENTICE 55%", group: "PIPEFITTER TM", baseSt: 28.39, st: 74.31, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER APPRENTICE 60%", group: "PIPEFITTER TM", baseSt: 30.97, st: 77.44, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER APPRENTICE 65%", group: "PIPEFITTER TM", baseSt: 33.55, st: 80.57, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER APPRENTICE 70%", group: "PIPEFITTER TM", baseSt: 36.13, st: 83.7, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER APPRENTICE 75%", group: "PIPEFITTER TM", baseSt: 38.71, st: 86.82, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER APPRENTICE 80%", group: "PIPEFITTER TM", baseSt: 41.29, st: 89.95, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER APPRENTICE 85%", group: "PIPEFITTER TM", baseSt: 43.87, st: 93.08, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER APPRENTICE 90%", group: "PIPEFITTER TM", baseSt: 46.45, st: 96.21, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER APPRENTICE 95%", group: "PIPEFITTER TM", baseSt: 46.58, st: 96.36, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER STEWARD 01", group: "PIPEFITTER TM", baseSt: 53.93, st: 105.28, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "BOILERMAKER GENERAL FOREMAN", group: "BOILERMAKER TM", baseSt: 50.6, st: 114.44, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "BOILERMAKER FOREMAN", group: "BOILERMAKER TM", baseSt: 49.1, st: 112.62, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "BOILERMAKER JOURNEYMAN", group: "BOILERMAKER TM", baseSt: 45.6, st: 108.38, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "APPRENTICE BOILERMAKER 70%", group: "BOILERMAKER TM", baseSt: 33.6, st: 93.83, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "APPRENTICE BOILERMAKER 72.5%", group: "BOILERMAKER TM", baseSt: 34.8, st: 95.29, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "APPRENTICE BOILERMAKER 75%", group: "BOILERMAKER TM", baseSt: 36, st: 96.74, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "APPRENTICE BOILERMAKER 77.5%", group: "BOILERMAKER TM", baseSt: 37.2, st: 98.2, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "APPRENTICE BOILERMAKER 80%", group: "BOILERMAKER TM", baseSt: 38.4, st: 99.65, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "APPRENTICE BOILERMAKER 85%", group: "BOILERMAKER TM", baseSt: 40.8, st: 102.56, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "APPRENTICE BOILERMAKER 90%", group: "BOILERMAKER TM", baseSt: 43.2, st: 105.47, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "APPRENTICE BOILERMAKER 95%", group: "BOILERMAKER TM", baseSt: 43.32, st: 105.61, ot: null, dt: null, pd: null, wageSource: "comp" },
];

export const MONROE_WAGE: ShahanLaborRow[] = [
  { craftName: "BOILERMAKER, GEN FOREMAN 01", group: "MEBM - Boilermaker", baseSt: 68, st: 140.47, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "BOILERMAKER, GEN FOREMAN 02", group: "MEBM - Boilermaker", baseSt: 64, st: 134.7, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "BOILERMAKER, FOREMAN", group: "MEBM - Boilermaker", baseSt: 62, st: 131.82, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "BOILERMAKER, JOURNEYMAN", group: "MEBM - Boilermaker", baseSt: 58, st: 126.05, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "BOILERMAKER, APPR 1ST P", group: "MEBM - Boilermaker", baseSt: 37.7, st: 96.76, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "BOILERMAKER, APPR 2ND P", group: "MEBM - Boilermaker", baseSt: 37.7, st: 96.76, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "BOILERMAKER, APPR 3RD P", group: "MEBM - Boilermaker", baseSt: 40.6, st: 100.94, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "BOILERMAKER, APPR 4TH P", group: "MEBM - Boilermaker", baseSt: 43.5, st: 105.13, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "BOILERMAKER, APPR 5TH P", group: "MEBM - Boilermaker", baseSt: 46.4, st: 109.31, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "BOILERMAKER, APPR 6TH P", group: "MEBM - Boilermaker", baseSt: 49.3, st: 113.5, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "BOILERMAKER, APPR 7TH P", group: "MEBM - Boilermaker", baseSt: 52.2, st: 117.68, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "BOILERMAKER, APPR 8TH P", group: "MEBM - Boilermaker", baseSt: 55.1, st: 121.86, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PF, GEN FMN, 2+ FMN, UP TO 100", group: "MEPF - Pipefitter", baseSt: 86.39, st: 177.72, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PF, GEN FMN, 101+ JRYMN", group: "MEPF - Pipefitter", baseSt: 90.14, st: 183.14, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER, FOREMAN, 2-5", group: "MEPF - Pipefitter", baseSt: 80.38, st: 169.05, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER, FOREMAN, UP TO 10", group: "MEPF - Pipefitter", baseSt: 82.63, st: 172.3, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER, FOREMAN, AREA", group: "MEPF - Pipefitter", baseSt: 84.13, st: 174.47, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER, WELDER, FOREMAN", group: "MEPF - Pipefitter", baseSt: 82.63, st: 172.3, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER, JOURNEYMAN", group: "MEPF - Pipefitter", baseSt: 75.12, st: 161.47, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER, APPR 1ST P", group: "MEPF - Pipefitter", baseSt: 30.05, st: 73.7, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER, APPR 2ND P", group: "MEPF - Pipefitter", baseSt: 30.05, st: 73.7, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER, APPR 3RD P", group: "MEPF - Pipefitter", baseSt: 33.8, st: 85.46, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER, APPR 4TH P", group: "MEPF - Pipefitter", baseSt: 33.8, st: 85.46, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER, APPR 5TH P", group: "MEPF - Pipefitter", baseSt: 41.32, st: 102.55, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER, APPR 6TH P", group: "MEPF - Pipefitter", baseSt: 41.32, st: 102.55, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER, APPR 7TH P", group: "MEPF - Pipefitter", baseSt: 48.83, st: 114.88, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER, APPR 8TH P", group: "MEPF - Pipefitter", baseSt: 48.83, st: 114.88, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER, APPR 9TH P", group: "MEPF - Pipefitter", baseSt: 56.34, st: 127.22, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PIPEFITTER, APPR 10TH P", group: "MEPF - Pipefitter", baseSt: 56.34, st: 127.22, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "BM SUPERINTENDENT 1", group: "MECBA - CBA Represented - Staff", baseSt: 87.02, st: 165.11, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PF SUPERINTENDENT (420) 2", group: "MECBA - CBA Represented - Staff", baseSt: 90.02, st: 180.16, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "BM Planner 1", group: "MECBA - CBA Represented - Staff", baseSt: 58, st: 123.25, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PF Planner (420) 2", group: "MECBA - CBA Represented - Staff", baseSt: 88, st: 177.25, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LEAD QA/QC (475) 1", group: "MECBA - CBA Represented - Staff", baseSt: 87.02, st: 175.83, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "SITE LEAD 01", group: "STAFF - General Field & Office - Staff", baseSt: 100.02, st: 159.05, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "MANAGER PROJECT 01", group: "STAFF - General Field & Office - Staff", baseSt: 98.02, st: 156.08, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "SUPERINTENDENT 01", group: "STAFF - General Field & Office - Staff", baseSt: 94.4, st: 150.72, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "SUPERINTENDENT 02", group: "STAFF - General Field & Office - Staff", baseSt: 96.02, st: 153.12, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "SUPERVISOR-01", group: "STAFF - General Field & Office - Staff", baseSt: 94.02, st: 150.15, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "SUPERVISOR-02", group: "STAFF - General Field & Office - Staff", baseSt: 92.4, st: 147.75, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PLANNER/ESTIMATOR 01", group: "STAFF - General Field & Office - Staff", baseSt: 90.4, st: 144.79, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "PLANNER-SCHEDULER 01", group: "STAFF - General Field & Office - Staff", baseSt: 92.02, st: 147.19, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LEAD QA/QC 01", group: "STAFF - General Field & Office - Staff", baseSt: 89.02, st: 142.74, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LEAD QA/QC 02", group: "STAFF - General Field & Office - Staff", baseSt: 85.4, st: 137.37, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR QA-QC 01", group: "STAFF - General Field & Office - Staff", baseSt: 65, st: 107.13, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR QA-QC 02", group: "STAFF - General Field & Office - Staff", baseSt: 62, st: 102.68, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "LEAD SAFETY 01", group: "STAFF - General Field & Office - Staff", baseSt: 65, st: 107.13, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR SAFETY 01", group: "STAFF - General Field & Office - Staff", baseSt: 62, st: 102.68, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR SAFETY 02", group: "STAFF - General Field & Office - Staff", baseSt: 60, st: 99.71, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "COORDINATOR MATERIAL 01", group: "STAFF - General Field & Office - Staff", baseSt: 58, st: 96.75, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "ATTENDANT TOOLROOM 01", group: "STAFF - General Field & Office - Staff", baseSt: 58, st: 96.75, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "EXPEDITOR 01", group: "STAFF - General Field & Office - Staff", baseSt: 58, st: 96.75, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "CLERK FIELD 01", group: "STAFF - General Field & Office - Staff", baseSt: 40, st: 70.06, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "MANAGER OFFICE 01", group: "STAFF - General Field & Office - Staff", baseSt: 50, st: 84.89, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "CLERK TIMEKEEPER 01", group: "STAFF - General Field & Office - Staff", baseSt: 45, st: 77.47, ot: null, dt: null, pd: null, wageSource: "comp" },
  { craftName: "CLERK TIMEKEEPER 02", group: "STAFF - General Field & Office - Staff", baseSt: 42, st: 73.02, ot: null, dt: null, pd: null, wageSource: "comp" },
];

export const YATES_WAGE: ShahanLaborRow[] = [
  { craftName: "Sr. Project Manager (Merit)", group: "Staff", baseSt: 95, st: 159.3275, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Sr. Project Manager (Union)", group: "Staff", baseSt: 85, st: 157.4125, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Project Manager (Merit)", group: "Staff", baseSt: 90, st: 151.495, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Project Manager (Union)", group: "Staff", baseSt: 80, st: 149.58, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Superintendent (Merit)", group: "Staff", baseSt: 85, st: 143.6625, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Superintendent (Union)", group: "Staff", baseSt: 65, st: 126.0825, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "QA/QC Lead (Merit)", group: "Staff", baseSt: 62.5, st: 108.41625, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "QA/QC Lead (Union)", group: "Staff", baseSt: 60, st: 118.25, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "QA/QC Tech (Merit)", group: "Staff", baseSt: 62.5, st: 108.41625, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "QA/QC Tech (Union)", group: "Staff", baseSt: 50, st: 102.585, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Safety Lead", group: "Staff", baseSt: 62.5, st: 108.41625, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Safety Tech (Merit)", group: "Staff", baseSt: 50, st: 88.835, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Safety Tech (Union)", group: "Staff", baseSt: 45, st: 94.7525, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Engineer Lead", group: "Staff", baseSt: 70, st: 120.165, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Field Engineer", group: "Staff", baseSt: 65, st: 112.3325, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "TimeKeeper", group: "Staff", baseSt: 55, st: 96.6675, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Field Clerk", group: "Craft", baseSt: 40, st: 75.77, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Tool Room", group: "Craft", baseSt: 34.21, st: 97.6775, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Boilermaker General Foreman", group: "Craft", baseSt: 41.51, st: 105.835, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Boilermaker Foreman", group: "Craft", baseSt: 39.51, st: 104.2035, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Boilermaker Assistant Foreman", group: "Craft", baseSt: 38.26, st: 102.572, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Boilermaker CPW-Tig Welder", group: "Craft", baseSt: 37.51, st: 100.9405, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Boilermaker CW-Mig Welder", group: "Craft", baseSt: 36.26, st: 100.9405, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Boilermaker Mechanic", group: "Craft", baseSt: 34.21, st: 100.9405, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Boilermaker Apprentice 95%", group: "Craft", baseSt: 32.5, st: 77.28375, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Boilermaker Apprentice 90%", group: "Craft", baseSt: 30.79, st: 74.493885, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Boilermaker Apprentice 85%", group: "Craft", baseSt: 29.08, st: 71.70402, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Boilermaker Apprentice 80%", group: "Craft", baseSt: 27.37, st: 68.914155, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Boilermaker Apprentice 75%", group: "Craft", baseSt: 25.66, st: 66.12429, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Boilermaker Apprentice 70%", group: "Craft", baseSt: 23.95, st: 63.334425, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Boilermaker Apprentice 65% (Probation Period)", group: "Craft", baseSt: 22.94, st: 61.68661, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Boilermaker Helper (Over 4,000)", group: "Craft", baseSt: 27.37, st: 68.914155, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Boilermaker Helper (1,000 - 2,000) Probationary", group: "Craft", baseSt: 20.53, st: 57.754695, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Boilermaker Helper (0-1,000) Probationary", group: "Craft", baseSt: 20.53, st: 57.754695, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Laborer Group 1", group: "Craft", baseSt: 17.74, st: 36.82281, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Laborer Group 2", group: "Craft", baseSt: 20.16, st: 40.77104, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Laborer Group 3", group: "Craft", baseSt: 21.53, st: 43.006195, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Laborer Apprentice 80%", group: "Craft", baseSt: 17.224, st: 35.980956, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Laborer Apprentice 85%", group: "Craft", baseSt: 18.3005, st: 37.73726575, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Laborer Apprentice 90%", group: "Craft", baseSt: 19.377, st: 39.4935755, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Laborer Apprentice 95%", group: "Craft", baseSt: 20.4535, st: 41.24988525, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Operator Group A", group: "Craft", baseSt: 37.53, st: 76.260195, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Operator Group A-2", group: "Craft", baseSt: 39.77, st: 79.914755, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Operator Group A-3", group: "Craft", baseSt: 40.91, st: 81.774665, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Operator Group A-4", group: "Craft", baseSt: 43.15, st: 85.429225, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Operator Group B", group: "Craft", baseSt: 32.2, st: 67.5643, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Operator Group C", group: "Craft", baseSt: 28.27, st: 61.152505, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Operator Group D", group: "Craft", baseSt: 21.47, st: 50.058305, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Operator Group E Apprentice 95%", group: "Craft", baseSt: 31.255, st: 66.0225325, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Operator Group E Apprentice 91%", group: "Craft", baseSt: 29.939, st: 63.8754785, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Operator Group E Apprentice 86%", group: "Craft", baseSt: 28.294, st: 61.191661, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Operator Group E Apprentice 82%", group: "Craft", baseSt: 26.978, st: 59.044607, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Operator Group E Apprentice 77%", group: "Craft", baseSt: 25.333, st: 56.3607895, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Operator Group E Apprentice 73%", group: "Craft", baseSt: 24.017, st: 54.2137355, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Operator Group E Apprentice 70%", group: "Craft", baseSt: 23.03, st: 52.603445, ot: null, dt: null, pd: null, wageSource: "shahan" },
  { craftName: "Operator Group E Apprentice 68%", group: "Craft", baseSt: 31.47872, st: 66.38753168, ot: null, dt: null, pd: null, wageSource: "shahan" },
];
