import type { EstimateRecord, ForgebookBoard, RateLine, SiteRecord } from "./types.ts";

const OWNER = "owner-robert-henderson";

const SITES: SiteRecord[] = [
  {
    id: "site-yates",
    ownerId: OWNER,
    code: "GP-YATES",
    name: "Yates",
    client: "Georgia Power",
    family: "Georgia Power",
    city: "Newnan, GA",
    openJobs: 0,
    plant: "Yates generating station",
    units: ["Outage window"],
    state: "Georgia",
    turnaround: "As released",
    contract: "As bid",
    gate: "Plant security",
    notes: "Georgia Power tile on the Madison desk.",
  },
  {
    id: "site-rodeo",
    ownerId: OWNER,
    code: "P66-RODEO",
    name: "Rodeo",
    client: "Phillips 66",
    family: "Phillips 66",
    city: "Rodeo, CA",
    openJobs: 0,
    plant: "Rodeo refinery",
    units: ["Process units"],
    state: "California",
    turnaround: "As released",
    contract: "Master T&M",
    gate: "Contractor gate",
    notes: "P66 plant card.",
  },
  {
    id: "site-bayway",
    ownerId: OWNER,
    code: "P66-BAYWAY",
    name: "Bayway",
    client: "Phillips 66",
    family: "Phillips 66",
    city: "Linden, NJ",
    openJobs: 0,
    plant: "Bayway refinery",
    units: ["Process units"],
    state: "New Jersey",
    turnaround: "As released",
    contract: "Master T&M",
    gate: "Contractor gate",
    notes: "P66 plant card.",
  },
  {
    id: "site-ferndale",
    ownerId: OWNER,
    code: "P66-FERN",
    name: "Ferndale",
    client: "Phillips 66",
    family: "Phillips 66",
    city: "Ferndale, WA",
    openJobs: 0,
    plant: "Ferndale refinery",
    units: ["Process units"],
    state: "Washington",
    turnaround: "As released",
    contract: "Master T&M",
    gate: "Contractor gate",
    notes: "P66 plant card.",
  },
  {
    id: "site-madison",
    ownerId: OWNER,
    code: "P66-WR",
    name: "Wood River",
    client: "Phillips 66",
    family: "Phillips 66",
    city: "Roxana, IL",
    openJobs: 0,
    plant: "Wood River refining complex",
    units: ["Unit 3 crude / vacuum", "Coker", "Flare & piperack", "Cooling towers"],
    state: "Illinois",
    turnaround: "As released",
    contract: "Master T&M + discrete lump-sum packages",
    gate: "North contractor gate · badge + TWIC",
    notes: "Client and contractor records are loaded for estimating only. Not Madison software.",
  },
  {
    id: "site-billings",
    ownerId: OWNER,
    code: "P66-BILL",
    name: "Billings",
    client: "Phillips 66",
    family: "Phillips 66",
    city: "Billings, MT",
    openJobs: 0,
    plant: "Billings refinery",
    units: ["Process units"],
    state: "Montana",
    turnaround: "As released",
    contract: "Master T&M",
    gate: "Contractor gate",
    notes: "P66 plant card.",
  },
  {
    id: "site-coker-pad",
    ownerId: OWNER,
    code: "P66-CKR",
    name: "Coker pad / drum alley",
    client: "Phillips 66",
    family: "Phillips 66",
    city: "Roxana, IL",
    openJobs: 0,
    plant: "Delayed coker",
    units: ["Drum A/B", "Switch deck", "Blowdown"],
    state: "Illinois",
    turnaround: "As released",
    contract: "Time & material, weekly ticket",
    gate: "Coker sally port",
    notes: "Hot work and confined-space control stay with the HSE rail.",
  },
];

const RATES: RateLine[] = [
  { id: "rt-1", ownerId: OWNER, craft: "Boilermaker", state: "IL", base: 48.75, fica: 7.65, fui: 0.6, sui: 3.15, wc: 11.4, gl: 2.1, smallTools: 1.5, burdened: 71.42 },
  { id: "rt-2", ownerId: OWNER, craft: "Pipefitter", state: "IL", base: 51.2, fica: 7.65, fui: 0.6, sui: 3.15, wc: 10.8, gl: 2.1, smallTools: 1.5, burdened: 75.01 },
  { id: "rt-3", ownerId: OWNER, craft: "Ironworker", state: "IL", base: 47.1, fica: 7.65, fui: 0.6, sui: 3.15, wc: 12.2, gl: 2.1, smallTools: 1.5, burdened: 69.0 },
  { id: "rt-4", ownerId: OWNER, craft: "Electrician", state: "IL", base: 52.4, fica: 7.65, fui: 0.6, sui: 3.15, wc: 6.8, gl: 2.1, smallTools: 1.75, burdened: 74.16 },
  { id: "rt-5", ownerId: OWNER, craft: "Operator", state: "IL", base: 44.8, fica: 7.65, fui: 0.6, sui: 3.15, wc: 8.9, gl: 2.1, smallTools: 1.25, burdened: 65.63 },
  { id: "rt-6", ownerId: OWNER, craft: "Laborer", state: "IL", base: 32.15, fica: 7.65, fui: 0.6, sui: 3.15, wc: 9.6, gl: 2.1, smallTools: 1.0, burdened: 47.48 },
  { id: "rt-7", ownerId: OWNER, craft: "Foreman", state: "IL", base: 58.0, fica: 7.65, fui: 0.6, sui: 3.15, wc: 10.8, gl: 2.1, smallTools: 1.5, burdened: 84.97 },
  { id: "rt-8", ownerId: OWNER, craft: "Safety attendant", state: "IL", base: 36.4, fica: 7.65, fui: 0.6, sui: 3.15, wc: 7.2, gl: 2.1, smallTools: 0.75, burdened: 53.35 },
];

function emptyRows(rates: RateLine[] = []): Omit<ForgebookBoard, "sites"> {
  return {
    estimates: [],
    crews: [],
    activities: [],
    equipment: [],
    staffing: [],
    changeOrders: [],
    rates,
    hse: [],
    quality: [],
    cost: [],
  };
}

export function boardForUser(userId: string): ForgebookBoard {
  return {
    sites: SITES,
    ...emptyRows(userId === OWNER ? RATES : []),
  };
}

export function estimateForUser(userId: string, estimateId: string): EstimateRecord | undefined {
  return boardForUser(userId).estimates.find((row) => row.id === estimateId);
}
