import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, it } from "node:test";

describe("home tree look batch", () => {
  it("keeps Inbox off the estimate toolbar and unread contrast off the trial orange", () => {
    const workspace = readFileSync(fileURLToPath(new URL("../components/EstimateWorkspace.tsx", import.meta.url)), "utf8");
    const chrome = readFileSync(fileURLToPath(new URL("../components/DeskChrome.tsx", import.meta.url)), "utf8");
    const fabs = readFileSync(fileURLToPath(new URL("../components/DeskFabs.tsx", import.meta.url)), "utf8");
    const theme = readFileSync(fileURLToPath(new URL("../components/ThemeFlip.tsx", import.meta.url)), "utf8");
    const dock = readFileSync(fileURLToPath(new URL("../components/HomeDock.tsx", import.meta.url)), "utf8");
    const crew = readFileSync(fileURLToPath(new URL("../components/CraftLaborGrid.tsx", import.meta.url)), "utf8");
    const css = readFileSync(fileURLToPath(new URL("../app/globals.css", import.meta.url)), "utf8");
    assert.equal(/InboxBadge/.test(workspace), false);
    assert.equal(/InboxBadge/.test(chrome), false);
    assert.equal(/InboxBadge/.test(fabs), false);
    assert.match(workspace, /title=\{item\.label\}/);
    assert.match(theme, /desk-hover-tip/);
    assert.match(theme, /title=\{/);
    assert.match(dock, /title=\{tile\.note\}/);
    assert.match(chrome, /title=\{item\.label\}/);
    assert.match(fabs, /title=\{inbox\.unread > 0 \? `Inbox · \$\{inbox\.unread\} unread` : "Inbox"\}/);
    assert.match(crew, /staff-clock-fold/);
    assert.match(crew, /<details className="staff-clock-fold">/);
    assert.match(crew, /Staff clock/);
    assert.match(css, /teal-pulse/);
    assert.match(css, /\.inbox-fab-pulse \{\n  animation: teal-pulse 1\.4s ease-out infinite;\n  background: #0f5f6d;/);
    assert.match(css, /\.inbox-header-badge \{\n  border-radius: 999px;\n  background: #0f5f6d;/);
    assert.match(css, /\.inbox-count \{[\s\S]*background: #fff;[\s\S]*color: #08343c;/);
    assert.match(css, /\.desk-hover-tip-label \{/);
    assert.match(css, /\.staff-clock-fold \{/);
    assert.match(css, /\.trial-banner \{[\s\S]*#e38b2a/);
    assert.match(css, /\.hero-company-logo \{/);
    assert.match(css, /\.hero-company-logo img \{/);
    assert.match(css, /object-fit: contain;/);
    const home = readFileSync(fileURLToPath(new URL("../components/DeskHome.tsx", import.meta.url)), "utf8");
    const hero = readFileSync(fileURLToPath(new URL("../components/DeskHero.tsx", import.meta.url)), "utf8");
    assert.match(home, /companyDeskLogo/);
    assert.match(hero, /hero-company-logo/);
    assert.match(hero, /HomeDock/);
    assert.match(hero, /HOME_WORDMARK/);
    assert.match(css, /\.org-chart-desk \{/);
    assert.match(css, /\.org-chart-card \{/);
    assert.match(css, /\.org-chart-logo img \{/);
  });
});
